// db erd for lxp app
// created using dbml
// docs : https://dbml.dbdiagram.io/docs/

Table users {
  id serial [pk]
  email varchar [unique]
  password varchar
  name varchar
}

Table students {
  id serial [pk]
  user_id integer
  some_info varchar
}
Ref: students.user_id > users.id

Table course_enrollments {
  id serial [pk]
  user_id integer
  course_id integer
  is_completed boolean
  completion_percentage integer
}
Ref: course_enrollments.course_id > courses.id
Ref: course_enrollments.user_id > users.id


Table instructors {
  id serial [pk]
  user_id integer
  some_info varchar
}
Ref: instructors.user_id > users.id


Table courses {
  id serial [pk]
  instructor_id integer
  title varchar
  caption text
  description text
}
Ref: courses.instructor_id > instructors.id

Table chapters {
  id serial [pk]
  courses_id integer
  title varchar
}
Ref: chapters.courses_id > courses.id

Table topics {
  id serial [pk]
  chapter_id integer
  title varchar
  sort_order integer
  type topic_type
}
Ref: topics.chapter_id > chapters.id

Enum topic_type {
  lesson
  practice
}

Table lessons {
  id serial [pk]
  topic_id integer
  title varchar
  type lesson_type
}
Ref: lessons.topic_id > topics.id

enum lesson_type {
  video
  pdf
  article
}

Table lesson_videos {
  id serial [pk]
  lesson_id integer
  video_url varchar
}
Ref: lesson_videos.lesson_id > lessons.id

Table lesson_pdfs {
  id serial [pk]
  lesson_id integer
  pdf_url varchar
}
Ref: lesson_pdfs.lesson_id > lessons.id

Table lesson_articles {
  id serial [pk]
  lesson_id integer
  content text
}
Ref: lesson_articles.lesson_id > lessons.id

Table practices {
  id serial [pk]
  topic_id integer
  title varchar
  type practice_type
}
Ref: practices.topic_id > topics.id

Enum practice_type {
  single_choice
  code_challenge
  open_question
}

Table practice_single_choice_questions {
  id serial [pk]
  practice_id integer [ref: > practices.id]
  question text
  image_url varchar
}

Table practice_single_choice_options {
  id serial [pk]
  question_id integer [ref: > practice_single_choice_questions.id]
  description text
  is_correct boolean
}

Table practice_single_choice_user_answers {
  is serial [pk]
  user_id integer [ref: > users.id]
  question_id integer [ref: > practice_single_choice_questions.id]
  selected_option_id integer [ref: > practice_single_choice_options.id]
  is_correct boolean
}

Table practice_single_choice_user_result {
  id serial [pk]
  user_id integer [ref: > users.id]
  practice_id integer [ref: > practices.id]
  correct_questions integer
  total_questions integer
}
